"""empty message

Revision ID: 861d499a67d6
Revises: dedaaa67af68
Create Date: 2024-10-31 16:45:37.597537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861d499a67d6'
down_revision = 'dedaaa67af68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
